import type { Delegacion, Cuenta, Categoria, Movimiento } from "./types"

// Mock data for development
export const mockDelegaciones: Delegacion[] = [
  {
    id: "del-1",
    organizacion_id: "org-1",
    codigo: "MAD",
    nombre: "Madrid Central",
    creado_en: "2024-01-01T00:00:00Z",
  },
  {
    id: "del-2",
    organizacion_id: "org-1",
    codigo: "BCN",
    nombre: "Barcelona Norte",
    creado_en: "2024-01-01T00:00:00Z",
  },
  {
    id: "del-3",
    organizacion_id: "org-1",
    codigo: "SEV",
    nombre: "Sevilla Sur",
    creado_en: "2024-01-01T00:00:00Z",
  },
]

export const mockCuentas: Cuenta[] = [
  {
    id: "cuenta-1",
    delegacion_id: "del-1",
    nombre: "Cuenta Principal",
    tipo: "banco",
    origen: "conectada",
    banco_nombre: "Banco Santander",
    iban: "ES91 2100 0418 4502 0005 1332",
    creado_en: "2024-01-01T00:00:00Z",
  },
  {
    id: "cuenta-2",
    delegacion_id: "del-1",
    nombre: "Caja Chica",
    tipo: "caja",
    origen: "manual",
    banco_nombre: null,
    iban: null,
    creado_en: "2024-01-01T00:00:00Z",
  },
  {
    id: "cuenta-3",
    delegacion_id: "del-1",
    nombre: "Tarjeta de Crédito",
    tipo: "banco",
    origen: "conectada",
    banco_nombre: "BBVA",
    iban: "ES76 0182 1111 2806 3030 2035",
    creado_en: "2024-01-01T00:00:00Z",
  },
]

export const mockCategorias: Categoria[] = [
  {
    id: "cat-1",
    organizacion_id: "org-1",
    nombre: "Ventas",
    tipo: "ingreso",
    emoji: "💰",
    orden: 1,
    categoria_padre_id: null,
    creado_en: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-2",
    organizacion_id: "org-1",
    nombre: "Préstamos bancarios",
    tipo: "gasto",
    emoji: "🏦",
    orden: 2,
    categoria_padre_id: null,
    creado_en: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-3",
    organizacion_id: "org-1",
    nombre: "Nóminas",
    tipo: "gasto",
    emoji: "💼",
    orden: 3,
    categoria_padre_id: null,
    creado_en: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-4",
    organizacion_id: "org-1",
    nombre: "Marketing",
    tipo: "gasto",
    emoji: "📢",
    orden: 4,
    categoria_padre_id: null,
    creado_en: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-5",
    organizacion_id: "org-1",
    nombre: "Alquiler oficina",
    tipo: "gasto",
    emoji: "🏢",
    orden: 5,
    categoria_padre_id: null,
    creado_en: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-6",
    organizacion_id: "org-1",
    nombre: "Suministros",
    tipo: "gasto",
    emoji: "💡",
    orden: 6,
    categoria_padre_id: null,
    creado_en: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-7",
    organizacion_id: "org-1",
    nombre: "Software y suscripciones",
    tipo: "gasto",
    emoji: "💻",
    orden: 7,
    categoria_padre_id: null,
    creado_en: "2024-01-01T00:00:00Z",
  },
]

export const mockMovimientos: Movimiento[] = [
  {
    id: "mov-1",
    cuenta_id: "cuenta-1",
    fecha: "2025-01-11",
    concepto: "Cabify business",
    descripcion: "Transporte para reunión cliente",
    texto_extra_1: null,
    texto_extra_2: null,
    contraparte: "Cabify España",
    importe: -45.88,
    metodo: "tarjeta",
    notas: null,
    ignorado: false,
    categoria_id: null,
    adjunto_principal_url: null,
    creado_por: "user-1",
    creado_en: "2025-01-11T10:30:00Z",
  },
  {
    id: "mov-2",
    cuenta_id: "cuenta-1",
    fecha: "2025-01-11",
    concepto: "Ventas tpv online ES",
    descripcion: "Venta productos online España",
    texto_extra_1: null,
    texto_extra_2: null,
    contraparte: "Stripe Payments",
    importe: 734.89,
    metodo: "transferencia",
    notas: null,
    ignorado: false,
    categoria_id: "cat-1",
    adjunto_principal_url: null,
    creado_por: "user-1",
    creado_en: "2025-01-11T14:22:00Z",
  },
  {
    id: "mov-3",
    cuenta_id: "cuenta-1",
    fecha: "2025-01-11",
    concepto: "Ventas tpv online PT",
    descripcion: "Venta productos online Portugal",
    texto_extra_1: null,
    texto_extra_2: null,
    contraparte: "Stripe Payments",
    importe: 261.93,
    metodo: "transferencia",
    notas: null,
    ignorado: false,
    categoria_id: "cat-1",
    adjunto_principal_url: null,
    creado_por: "user-1",
    creado_en: "2025-01-11T16:45:00Z",
  },
  {
    id: "mov-4",
    cuenta_id: "cuenta-1",
    fecha: "2025-01-11",
    concepto: "Ventas tpv online US",
    descripcion: "Venta productos online Estados Unidos",
    texto_extra_1: null,
    texto_extra_2: null,
    contraparte: "Stripe Payments",
    importe: 393.59,
    metodo: "transferencia",
    notas: null,
    ignorado: false,
    categoria_id: "cat-1",
    adjunto_principal_url: null,
    creado_por: "user-1",
    creado_en: "2025-01-11T18:12:00Z",
  },
  {
    id: "mov-5",
    cuenta_id: "cuenta-3",
    fecha: "2025-01-10",
    concepto: "Vodafone",
    descripcion: "Factura mensual telefonía",
    texto_extra_1: null,
    texto_extra_2: null,
    contraparte: "Vodafone España",
    importe: -77.23,
    metodo: "domiciliacion",
    notas: null,
    ignorado: false,
    categoria_id: "cat-6",
    adjunto_principal_url: null,
    creado_por: "user-1",
    creado_en: "2025-01-10T09:15:00Z",
  },
  {
    id: "mov-6",
    cuenta_id: "cuenta-1",
    fecha: "2025-01-08",
    concepto: "Slack",
    descripcion: "Suscripción mensual Slack Pro",
    texto_extra_1: null,
    texto_extra_2: null,
    contraparte: "Slack Technologies",
    importe: -120.0,
    metodo: "tarjeta",
    notas: null,
    ignorado: false,
    categoria_id: "cat-7",
    adjunto_principal_url: null,
    creado_por: "user-1",
    creado_en: "2025-01-08T12:00:00Z",
  },
]
