-- 073 — Importación del Excel "AJMCM · Plan Subvenciones" (pestaña Lista Subvenciones)
--
-- Generado a partir del Excel de la oficina técnica. Necesita 071 y 072.
-- Idempotente: cada subvención se inserta solo si no existe ya una con el
-- mismo código, nombre, ejercicio, solicitante, financiador, convocatoria y
-- fecha de convocatoria; los financiadores, solo si no
-- existe uno con el mismo nombre. Se puede volver a ejecutar sin duplicar.
--
-- Cómo se ha leído cada columna:
--   A código · C financiador · D nombre (tipo de subvención) · E nombre oficial
--   (va a "convocatoria", plegado) · F estado · G "J" → justificación completa
--   · H importe: concedido si el estado es de concedida en adelante, si no,
--   solicitado · I solicitado · J delegación → "la pide" · K carpeta ·
--   L/M/N/O/P fechas · Q 🔁 → sale cada año · resto de enlaces → enlaces ·
--   comentarios de la fila y de las celdas → notas.
--   Las fechas escritas a mano ("junio 25??", "+3 meses desde firma") van a
--   notas tal cual. "7 Parcial 💸" → cobrada en parte, con el importe H como
--   cobrado.
--   Limpieza de 2023/2024 (y lo que arrastraban otros años): los comentarios
--   de celda copiados a filas de otros años se quedan solo en la primera; los
--   códigos que faltaban en 2023 se toman de la misma línea en 2024; fuera los
--   enlaces al propio Excel y los repetidos; un límite o una concesión
--   anteriores a la convocatoria (copiados de otro año) pasan a notas.
--   Al aplicarlo en producción (29/09/2026) se retocó además: en GVA VAL, GVA
--   ODS y GVA IRPF 2024 la "carpeta" era la web de la convocatoria (pasa a
--   enlaces); la 2ª justificación de GVA VOL 2024 repetía la 1ª (fuera); fuera
--   el enlace de Cultura 2023 que repetía su carpeta, y la nota duplicada de
--   Onda 2025. Esos retoques están en la base de datos, no en este archivo.
--   Bloque "CONVOCATORIAS PARA ESTUDIAR" y el catálogo del final (solo las que
--   nunca se han pedido) NO se importan: se decidió dejarlas fuera por ahora.

begin;

-- Financiadores, en el orden en que aparecen en el Excel (GVA arriba, lo local y lo raro abajo)
insert into public.financiador (nombre, ambito, orden) select 'GVA Inclusión', 'autonomico', 10 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión'));
update public.financiador set ambito = 'autonomico', orden = 10 where lower(btrim(nombre)) = lower('GVA Inclusión') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'GVA Participación', 'autonomico', 20 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('GVA Participación'));
update public.financiador set ambito = 'autonomico', orden = 20 where lower(btrim(nombre)) = lower('GVA Participación') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'GVA Educación', 'autonomico', 30 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('GVA Educación'));
update public.financiador set ambito = 'autonomico', orden = 30 where lower(btrim(nombre)) = lower('GVA Educación') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'GVA IRPF', 'autonomico', 40 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('GVA IRPF'));
update public.financiador set ambito = 'autonomico', orden = 40 where lower(btrim(nombre)) = lower('GVA IRPF') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'GVA IVAJ', 'autonomico', 50 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('GVA IVAJ'));
update public.financiador set ambito = 'autonomico', orden = 50 where lower(btrim(nombre)) = lower('GVA IVAJ') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'Ayto Onda', 'local', 60 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('Ayto Onda'));
update public.financiador set ambito = 'local', orden = 60 where lower(btrim(nombre)) = lower('Ayto Onda') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'Ayto CS', 'local', 70 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('Ayto CS'));
update public.financiador set ambito = 'local', orden = 70 where lower(btrim(nombre)) = lower('Ayto CS') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'Diputación CS', 'provincial', 80 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('Diputación CS'));
update public.financiador set ambito = 'provincial', orden = 80 where lower(btrim(nombre)) = lower('Diputación CS') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'Ayto Vila', 'local', 90 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('Ayto Vila'));
update public.financiador set ambito = 'local', orden = 90 where lower(btrim(nombre)) = lower('Ayto Vila') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'Didania', 'privado', 100 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('Didania'));
update public.financiador set ambito = 'privado', orden = 100 where lower(btrim(nombre)) = lower('Didania') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'Red.es', 'estatal', 110 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('Red.es'));
update public.financiador set ambito = 'estatal', orden = 110 where lower(btrim(nombre)) = lower('Red.es') and ambito = 'otro' and orden = 100;
insert into public.financiador (nombre, ambito, orden) select 'CES · Cuerpo Europeo de Solidaridad', 'europeo', 120 where not exists (select 1 from public.financiador where lower(btrim(nombre)) = lower('CES · Cuerpo Europeo de Solidaridad'));
update public.financiador set ambito = 'europeo', orden = 120 where lower(btrim(nombre)) = lower('CES · Cuerpo Europeo de Solidaridad') and ambito = 'otro' and orden = 100;

-- Subvenciones
-- fila 3
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA VOL', 'Fom. Voluntariado', 2026, 'solicitada', 'AJ', 15000.0, null, null, null, null, null, null, null, false, true, 'Convocatoria de subvenciones para el ejercicio 2023 a entidades privadas sin ánimo de lucro para la financiación de proyectos de proyectos y actividades de promoción y fomento del voluntariado en la Comunitat Valenciana', null, null, (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA VOL','') and nombre = 'Fom. Voluntariado' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión')) and convocatoria is not distinct from 'Convocatoria de subvenciones para el ejercicio 2023 a entidades privadas sin ánimo de lucro para la financiación de proyectos de proyectos y actividades de promoción y fomento del voluntariado en la Comunitat Valenciana' and fecha_convocatoria is not distinct from null::date);
-- fila 4
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA Part', 'Participación Ciudadana', 2026, 'solicitada', 'AJ', 8000.0, null, null, null, null, null, null, null, false, true, 'ESOLUCIÓN de la Conselleria de Participación, Transparencia, Cooperación y Calidad Democrática, por la que se efectúa la convocatoria, para el año 2023, de subvenciones destinadas a las entidades ciudadanas de la Comunitat Valenciana, para el fortalecimiento de la participación ciudadana en el ámbito del asociacionismo.', null, null, (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Participación')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA Part','') and nombre = 'Participación Ciudadana' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Participación')) and convocatoria is not distinct from 'ESOLUCIÓN de la Conselleria de Participación, Transparencia, Cooperación y Calidad Democrática, por la que se efectúa la convocatoria, para el año 2023, de subvenciones destinadas a las entidades ciudadanas de la Comunitat Valenciana, para el fortalecimiento de la participación ciudadana en el ámbito del asociacionismo.' and fecha_convocatoria is not distinct from null::date);
-- fila 5
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA ESAL', 'ESAL Intercultural', 2026, 'solicitada', 'AJ', 16467.03, null, null, null, null, null, null, null, false, false, 'Subvenciones destinadas a acciones y programas educativos innovadores que promuevan la educación intercultural y en valores desarrollados por entidades privadas sin ánimo de lucro en el territorio valenciano en el curso escolar 2022-2023 [RESOLUCIÓN de 3 de abril de 2023]', null, null, (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Educación')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA ESAL','') and nombre = 'ESAL Intercultural' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Educación')) and convocatoria is not distinct from 'Subvenciones destinadas a acciones y programas educativos innovadores que promuevan la educación intercultural y en valores desarrollados por entidades privadas sin ánimo de lucro en el territorio valenciano en el curso escolar 2022-2023 [RESOLUCIÓN de 3 de abril de 2023]' and fecha_convocatoria is not distinct from null::date);
-- fila 6
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA IRPF', 'Programas de Juventud - Equip', 2026, 'solicitada', 'AJ', 35192.58, null, null, null, null, null, null, null, false, false, null, null, null, (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IRPF')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA IRPF','') and nombre = 'Programas de Juventud - Equip' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IRPF')) and convocatoria is not distinct from null and fecha_convocatoria is not distinct from null::date);
-- fila 7
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'IVAJ', 'Entidades Juveniles', 2026, 'concedida', 'AJ', 94452.52, 67351.65, null, '2026-03-04', null, null, null, null, false, false, 'Asociaciones IVAJ', 'https://drive.google.com/drive/folders/1vnVP82_cyVnmo2WM9wit6RcC-_AaPNId', null, (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IVAJ')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('IVAJ','') and nombre = 'Entidades Juveniles' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IVAJ')) and convocatoria is not distinct from 'Asociaciones IVAJ' and fecha_convocatoria is not distinct from '2026-03-04'::date);
-- fila 9
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto Onda', 'Entidades Juveniles', 2026, 'concedida', 'Onda', 6567.0, 6567.0, null, '2026-02-21', null, null, '2026-10-01', null, false, true, 'BASES ESPECÍFICAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES A ASOCIACIONES Y ENTIDADES DE ONDA, SIN ÁNIMO DE LUCRO PARA LA REALIZACIÓN DE PROGRAMAS DE OCIO Y TIEMPO LIBRE DIRIGIDAS A LA POBLACIÓN JUVENIL DE ONDA (PRESUPUESTO 2023).', 'https://drive.google.com/drive/folders/1RCl47E2zxtAI9svi_6Qbd3JQFZ43r_Ae', 'Límite para solicitar en el Excel: 2025-03-19 (es anterior a la convocatoria: probablemente copiada de otro año, revísala)
Concesión en el Excel: 2025-04-24 (es anterior a la convocatoria: probablemente copiada de otro año, revísala)', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto Onda')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%onda%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto Onda','') and nombre = 'Entidades Juveniles' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'Onda' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto Onda')) and convocatoria is not distinct from 'BASES ESPECÍFICAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES A ASOCIACIONES Y ENTIDADES DE ONDA, SIN ÁNIMO DE LUCRO PARA LA REALIZACIÓN DE PROGRAMAS DE OCIO Y TIEMPO LIBRE DIRIGIDAS A LA POBLACIÓN JUVENIL DE ONDA (PRESUPUESTO 2023).' and fecha_convocatoria is not distinct from '2026-02-21'::date);
-- fila 10
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS', 'Entidades Juveniles', 2026, 'concedida', 'Castellón', 10255.0, 3484.75, null, '2026-03-31', null, null, null, null, false, true, 'Concessió de Subvencions a Entitats Juvenils per a l''execució d''activitats durant el període comprés entre l''1 de Juliol de 2023 i el 30 de juny de 2024', 'https://drive.google.com/drive/folders/1BlGs9rypUv8-sK_tN-KwmtJ5THnu5kIW', '3 actividades - Campamento y convi CS + Fiesta Delwende
Sobre el importe: 1º pago: 2.323,22€ 2º pago: 1.161,53€
Límite para solicitar en el Excel: 2025-03-18 (es anterior a la convocatoria: probablemente copiada de otro año, revísala)', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS','') and nombre = 'Entidades Juveniles' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Concessió de Subvencions a Entitats Juvenils per a l''execució d''activitats durant el període comprés entre l''1 de Juliol de 2023 i el 30 de juny de 2024' and fecha_convocatoria is not distinct from '2026-03-31'::date);
-- fila 11
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'DIP CS', 'Entidades Juveniles CS', 2026, 'solicitada', 'Castellón', 3000.0, null, null, '2026-02-19', null, null, '2026-12-31', null, false, true, 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023', 'https://drive.google.com/drive/folders/1mFhkU4kJfH--faWCjPW3vWhvYGje922R', 'Límite para solicitar en el Excel: 2025-05-29 (es anterior a la convocatoria: probablemente copiada de otro año, revísala)', (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('DIP CS','') and nombre = 'Entidades Juveniles CS' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')) and convocatoria is not distinct from 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023' and fecha_convocatoria is not distinct from '2026-02-19'::date);
-- fila 12
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'DIP NAC', 'Entidades Juveniles ZONA', 2026, 'solicitada', 'AJ', 3000.0, null, null, '2026-02-19', null, null, '2026-12-31', null, false, true, 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023', 'https://drive.google.com/drive/folders/1blZV2WTwCA016u6hjnRuzi5M4DpHF53c', 'Campamento COM Nacional
Límite para solicitar en el Excel: 2025-05-29 (es anterior a la convocatoria: probablemente copiada de otro año, revísala)', (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('DIP NAC','') and nombre = 'Entidades Juveniles ZONA' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')) and convocatoria is not distinct from 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023' and fecha_convocatoria is not distinct from '2026-02-19'::date);
-- fila 13
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto Vila', 'Campaments - Població jove', 2026, 'no_convocada', 'Vila-real', null, null, null, null, null, null, null, null, false, false, 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023', 'https://drive.google.com/drive/folders/1k9ygGvGnjGiTFK9-e2ikZirRuzSTLQZE', null, (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto Vila')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%vila%real%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto Vila','') and nombre = 'Campaments - Població jove' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'Vila-real' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto Vila')) and convocatoria is not distinct from 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023' and fecha_convocatoria is not distinct from null::date);
-- fila 15
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS Lan', 'Llamada a Proyectos: Lan Party 25', 2026, 'rechazada', 'Castellón', 2751.0, null, null, '2026-02-10', null, null, null, null, false, true, 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Abril 2024', 'https://drive.google.com/drive/folders/1alxnS8TET07Y1UIEHWdKkvfOZR5AT9En', null, (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS Lan','') and nombre = 'Llamada a Proyectos: Lan Party 25' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Abril 2024' and fecha_convocatoria is not distinct from '2026-02-10'::date);
-- fila 16
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS Cul', 'Cultura', 2026, 'renuncia', 'Castellón', null, null, null, null, null, null, null, null, false, false, 'BASES REGULADORAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES, POR PARTE DEL AYUNTAMIENTO DE CASTELLÓ DE LA PLANA, DESTINADAS A LA FINANCIACIÓN DE PROYECTOS DE DESARROLLO Y FOMENTO DE LA CULTURA QUE REALICEN LAS ASOCIACIONES CULTURALES DURANTE EL PERÍODO COMPRENDIDO ENTRE EL 1 DE ENERO Y EL 31 DE DICIEMBRE DE 2023', null, null, (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS Cul','') and nombre = 'Cultura' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'BASES REGULADORAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES, POR PARTE DEL AYUNTAMIENTO DE CASTELLÓ DE LA PLANA, DESTINADAS A LA FINANCIACIÓN DE PROYECTOS DE DESARROLLO Y FOMENTO DE LA CULTURA QUE REALICEN LAS ASOCIACIONES CULTURALES DURANTE EL PERÍODO COMPRENDIDO ENTRE EL 1 DE ENERO Y EL 31 DE DICIEMBRE DE 2023' and fecha_convocatoria is not distinct from null::date);
-- fila 18
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'DIDANIA', 'Didania - Sustancias', 2026, 'solicitada', 'AJ', null, null, null, null, null, null, null, null, false, false, null, null, 'Campamento COM Nacional', (select id from public.financiador where lower(btrim(nombre)) = lower('Didania')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('DIDANIA','') and nombre = 'Didania - Sustancias' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Didania')) and convocatoria is not distinct from null and fecha_convocatoria is not distinct from null::date);
-- fila 19
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'KIT ECE', 'Kit Digital AJ / ECE', 2026, 'no_convocada', 'ECE', null, null, null, null, null, null, null, null, false, false, null, null, 'Límite para solicitar: junio 25??', (select id from public.financiador where lower(btrim(nombre)) = lower('Red.es')), null, '[{"nombre": "Red.es", "url": "http://red.es/"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('KIT ECE','') and nombre = 'Kit Digital AJ / ECE' and ejercicio is not distinct from 2026::int and solicitante is not distinct from 'ECE' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Red.es')) and convocatoria is not distinct from null and fecha_convocatoria is not distinct from null::date);
-- fila 26
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA VOL', 'Fom. Voluntariado', 2025, 'rechazada', 'AJ', 15000.0, null, null, '2025-03-10', null, null, null, null, false, true, 'Convocatoria de subvenciones para el ejercicio 2023 a entidades privadas sin ánimo de lucro para la financiación de proyectos de proyectos y actividades de promoción y fomento del voluntariado en la Comunitat Valenciana', 'https://drive.google.com/drive/folders/167ojaBp4wrJpQab2hH0tAf3B8RTsDxCl?usp=drive_link', null, (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA VOL','') and nombre = 'Fom. Voluntariado' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión')) and convocatoria is not distinct from 'Convocatoria de subvenciones para el ejercicio 2023 a entidades privadas sin ánimo de lucro para la financiación de proyectos de proyectos y actividades de promoción y fomento del voluntariado en la Comunitat Valenciana' and fecha_convocatoria is not distinct from '2025-03-10'::date);
-- fila 27
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA Part', 'Participación Ciudadana', 2025, 'justificada', 'AJ', 8000.0, 5956.26, null, '2025-04-22', null, null, null, null, true, true, 'ESOLUCIÓN de la Conselleria de Participación, Transparencia, Cooperación y Calidad Democrática, por la que se efectúa la convocatoria, para el año 2023, de subvenciones destinadas a las entidades ciudadanas de la Comunitat Valenciana, para el fortalecimiento de la participación ciudadana en el ámbito del asociacionismo.', 'https://drive.google.com/drive/folders/1mhJszOLtDkMifeYUes7NyXA-GQDRpCEi', 'Hay que presentarse en modalida B local y puede que nos la den. Baja el presupuesto medio millón de euros
Sobre el importe: Nos conceden 8.000 € pero se minora el importe en 2.043,74 € por errores en la justificación - Pagado 2400 € en mayo 26', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Participación')), null, '[{"nombre": "2025 - GVA Participación ✅", "url": "https://drive.google.com/drive/folders/1mhJszOLtDkMifeYUes7NyXA-GQDRpCEi?usp=drive_link"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA Part','') and nombre = 'Participación Ciudadana' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Participación')) and convocatoria is not distinct from 'ESOLUCIÓN de la Conselleria de Participación, Transparencia, Cooperación y Calidad Democrática, por la que se efectúa la convocatoria, para el año 2023, de subvenciones destinadas a las entidades ciudadanas de la Comunitat Valenciana, para el fortalecimiento de la participación ciudadana en el ámbito del asociacionismo.' and fecha_convocatoria is not distinct from '2025-04-22'::date);
-- fila 28
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA ESAL', 'Educacion Intercultural y valores', 2025, 'renuncia', 'AJ', 4000.0, null, null, null, null, null, null, null, false, false, 'Subvenciones destinadas a acciones y programas educativos innovadores que promuevan la educación intercultural y en valores desarrollados por entidades privadas sin ánimo de lucro en el territorio valenciano en el curso escolar 2022-2023 [RESOLUCIÓN de 3 de abril de 2023]', null, 'Curso 2024-2025, aprovechar para presentar septiembre, octubre, noviembre, diciembre de 2023 - Llegamos tarde y no nos presentamos por error
Convocatoria: verano??
Tipo subvención: Nombre nuevo, ver', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Educación')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA ESAL','') and nombre = 'Educacion Intercultural y valores' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Educación')) and convocatoria is not distinct from 'Subvenciones destinadas a acciones y programas educativos innovadores que promuevan la educación intercultural y en valores desarrollados por entidades privadas sin ánimo de lucro en el territorio valenciano en el curso escolar 2022-2023 [RESOLUCIÓN de 3 de abril de 2023]' and fecha_convocatoria is not distinct from null::date);
-- fila 29
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA IRPF', 'Programas de Juventud - Equip', 2025, 'rechazada', 'AJ', 8819.2, null, null, '2025-08-25', null, null, null, null, false, false, null, null, 'No podíamos por dos años de antiguedad. Ver obras, equipamiento... hay versiones pequeñas', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IRPF')), null, '[{"nombre": "https://www.pap.hacienda.gob.es/bdnstrans/GE/es/convocatorias/770144", "url": "https://www.pap.hacienda.gob.es/bdnstrans/GE/es/convocatorias/770144"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA IRPF','') and nombre = 'Programas de Juventud - Equip' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IRPF')) and convocatoria is not distinct from null and fecha_convocatoria is not distinct from '2025-08-25'::date);
-- fila 30
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'IVAJ', 'Entidades Juveniles', 2025, 'cobrada', 'AJ', 70030.54, 55825.15, null, '2025-07-08', null, null, null, null, false, false, 'Asociaciones IVAJ', 'https://drive.google.com/drive/folders/1hwQ-UevcuZLjtCGKbxs80JdsiwIQB2kU', 'Estudiar. Contratación técnico + Curso MAT + Actividades grandes a cofinanciar.', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IVAJ')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('IVAJ','') and nombre = 'Entidades Juveniles' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IVAJ')) and convocatoria is not distinct from 'Asociaciones IVAJ' and fecha_convocatoria is not distinct from '2025-07-08'::date);
-- fila 32
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto Onda', 'Entidades Juveniles', 2025, 'cobrada', 'Onda', 12930.0, 6635.73, null, '2025-02-21', '2025-03-19', '2025-04-24', null, null, false, true, 'BASES ESPECÍFICAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES A ASOCIACIONES Y ENTIDADES DE ONDA, SIN ÁNIMO DE LUCRO PARA LA REALIZACIÓN DE PROGRAMAS DE OCIO Y TIEMPO LIBRE DIRIGIDAS A LA POBLACIÓN JUVENIL DE ONDA (PRESUPUESTO 2023).', 'https://drive.google.com/drive/folders/1nlLxMhVhZIDTQ7fm7Otx9gnnYIT79GoZ?usp=sharing', 'Dudas sobre la antiguedad
Sobre el importe: Nos conceden 8.682 € por los 12,9k pedidos. Solo justificamos 9.882,72 € y por lo tanto se reduce Desviación de -3.047,28€ que supone un 23 % del total En principio serán 6635,58
Sobre lo solicitado: Nos conceden 8.682 € por los 12,9k pedidos. Solo justificamos 9.882,72 € y por lo tanto se reduce', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto Onda')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%onda%'), '[{"nombre": "2025 - Onda Ayto", "url": "https://drive.google.com/drive/folders/1nlLxMhVhZIDTQ7fm7Otx9gnnYIT79GoZ?usp=drive_link"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto Onda','') and nombre = 'Entidades Juveniles' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'Onda' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto Onda')) and convocatoria is not distinct from 'BASES ESPECÍFICAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES A ASOCIACIONES Y ENTIDADES DE ONDA, SIN ÁNIMO DE LUCRO PARA LA REALIZACIÓN DE PROGRAMAS DE OCIO Y TIEMPO LIBRE DIRIGIDAS A LA POBLACIÓN JUVENIL DE ONDA (PRESUPUESTO 2023).' and fecha_convocatoria is not distinct from '2025-02-21'::date);
-- fila 33
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS', 'Entidades Juveniles', 2025, 'cobrada_parcial', 'Castellón', 8500.0, 3331.0, 3331.0, '2025-03-06', '2025-03-18', null, null, null, false, true, 'Concessió de Subvencions a Entitats Juvenils per a l''execució d''activitats durant el període comprés entre l''1 de Juliol de 2023 i el 30 de juny de 2024', 'https://drive.google.com/drive/folders/18RABkb_EGf9Vlturgg_Ncqo_h2ERYHbb', 'Campamento Consolación Castellón + otras 2 actividades
Sobre el importe: 1.608,18 €- Acampada COM 1.723,05 € - Campamento Pago anticipado: 2220,82 € Pago tras justificar: 1110,41 €', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS','') and nombre = 'Entidades Juveniles' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Concessió de Subvencions a Entitats Juvenils per a l''execució d''activitats durant el període comprés entre l''1 de Juliol de 2023 i el 30 de juny de 2024' and fecha_convocatoria is not distinct from '2025-03-06'::date);
-- fila 34
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'DIP CS', 'Entidades Juveniles CS', 2025, 'cobrada', 'Castellón', 3000.0, 3000.0, null, '2025-04-26', '2025-05-29', null, null, null, false, true, 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023', 'https://drive.google.com/drive/folders/1KENGxWJOmwP-eqy4iCMbglXBU-rEQ3su', 'Campamento Castellón - Solo presentar 5.000 €', (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('DIP CS','') and nombre = 'Entidades Juveniles CS' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')) and convocatoria is not distinct from 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023' and fecha_convocatoria is not distinct from '2025-04-26'::date);
-- fila 35
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'DIP VIL', 'Entidades Juveniles VILA', 2025, 'cobrada', 'Vila-real', 3000.0, 3000.0, null, '2025-04-26', '2025-05-29', null, null, null, false, true, 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023', 'https://drive.google.com/drive/folders/1KENGxWJOmwP-eqy4iCMbglXBU-rEQ3su', 'Campamento Vila-real- Solo presentar 5.000 €', (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%vila%real%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('DIP VIL','') and nombre = 'Entidades Juveniles VILA' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'Vila-real' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')) and convocatoria is not distinct from 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023' and fecha_convocatoria is not distinct from '2025-04-26'::date);
-- fila 37
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS Lan', 'Llamada a Proyectos: Lan Party 25', 2025, 'renuncia', 'Castellón', 2625.0, null, null, null, null, null, null, null, false, true, 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Abril 2024', 'https://drive.google.com/drive/folders/1lF2Vdjf56NMbt60ajy6OExsfxfdVLfpB?usp=drive_link', 'Lan Party 2025', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS Lan','') and nombre = 'Llamada a Proyectos: Lan Party 25' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Abril 2024' and fecha_convocatoria is not distinct from null::date);
-- fila 38
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS Cul', 'Cultura', 2025, 'renuncia', 'Castellón', 2500.0, null, null, null, null, null, null, null, false, false, 'BASES REGULADORAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES, POR PARTE DEL AYUNTAMIENTO DE CASTELLÓ DE LA PLANA, DESTINADAS A LA FINANCIACIÓN DE PROYECTOS DE DESARROLLO Y FOMENTO DE LA CULTURA QUE REALICEN LAS ASOCIACIONES CULTURALES DURANTE EL PERÍODO COMPRENDIDO ENTRE EL 1 DE ENERO Y EL 31 DE DICIEMBRE DE 2023', 'https://drive.google.com/drive/folders/1EiOGRvMf5HOKib8EWnUfVfdP42Dx33HO?usp=drive_link', 'Valorar nuevo musical Mª Rosa Molas, los gastos deben ejecutarse en 2024 - No nos presentamos, valoramos 2025, 2026', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS Cul','') and nombre = 'Cultura' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'BASES REGULADORAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES, POR PARTE DEL AYUNTAMIENTO DE CASTELLÓ DE LA PLANA, DESTINADAS A LA FINANCIACIÓN DE PROYECTOS DE DESARROLLO Y FOMENTO DE LA CULTURA QUE REALICEN LAS ASOCIACIONES CULTURALES DURANTE EL PERÍODO COMPRENDIDO ENTRE EL 1 DE ENERO Y EL 31 DE DICIEMBRE DE 2023' and fecha_convocatoria is not distinct from null::date);
-- fila 40
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'KIT ECE', 'Kit Digital AJ / ECE', 2025, 'por_solicitar', 'ECE', 3000.0, null, null, null, null, null, null, null, false, false, null, null, 'Valorar volver a presentarnos como ECE
Límite para solicitar: junio 25??', (select id from public.financiador where lower(btrim(nombre)) = lower('Red.es')), null, '[{"nombre": "Red.es", "url": "http://red.es/"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('KIT ECE','') and nombre = 'Kit Digital AJ / ECE' and ejercicio is not distinct from 2025::int and solicitante is not distinct from 'ECE' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Red.es')) and convocatoria is not distinct from null and fecha_convocatoria is not distinct from null::date);
-- fila 64
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA VOL', 'Fom. Voluntariado', 2024, 'cobrada', 'AJ', 15000.0, 15000.0, null, '2024-01-01', null, '2024-07-01', '2024-09-01', '2024-09-01', true, true, 'Convocatoria de subvenciones para el ejercicio 2023 a entidades privadas sin ánimo de lucro para la financiación de proyectos de proyectos y actividades de promoción y fomento del voluntariado en la Comunitat Valenciana', 'https://drive.google.com/drive/folders/17_I5in9UkNM_t8i37U0HOQhH6ExiXtgS?usp=drive_link', 'Ampliar a 15.000 € - Incluir hasta 7.000 € de sueldo técnico. Funciona correctamente y sin sorpresas. Curso MAT', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA VOL','') and nombre = 'Fom. Voluntariado' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión')) and convocatoria is not distinct from 'Convocatoria de subvenciones para el ejercicio 2023 a entidades privadas sin ánimo de lucro para la financiación de proyectos de proyectos y actividades de promoción y fomento del voluntariado en la Comunitat Valenciana' and fecha_convocatoria is not distinct from '2024-01-01'::date);
-- fila 65
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA Part', 'Participación Ciudadana', 2024, 'rechazada', 'AJ', 16000.0, null, null, '2024-01-01', null, '2024-06-01', null, null, false, true, 'ESOLUCIÓN de la Conselleria de Participación, Transparencia, Cooperación y Calidad Democrática, por la que se efectúa la convocatoria, para el año 2023, de subvenciones destinadas a las entidades ciudadanas de la Comunitat Valenciana, para el fortalecimiento de la participación ciudadana en el ámbito del asociacionismo.', null, 'Rechazada porque no llegaron los €€ a los puntos que teníamos. Hay que presentarse en modalida B local y nos la darán', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Participación')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA Part','') and nombre = 'Participación Ciudadana' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Participación')) and convocatoria is not distinct from 'ESOLUCIÓN de la Conselleria de Participación, Transparencia, Cooperación y Calidad Democrática, por la que se efectúa la convocatoria, para el año 2023, de subvenciones destinadas a las entidades ciudadanas de la Comunitat Valenciana, para el fortalecimiento de la participación ciudadana en el ámbito del asociacionismo.' and fecha_convocatoria is not distinct from '2024-01-01'::date);
-- fila 66
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'CES24', 'Cuerpo Europ. Solid. 2024 R1', 2024, 'rechazada', 'Castellón', 8000.0, null, null, '2024-02-20', null, '2024-06-30', null, null, false, false, 'Cuerpo Europeo de la Solidaridad - Ronda 2 - 2023', 'https://drive.google.com/drive/folders/1YoVRByPp_iI7WitGMcjqVoo3wU3vkMN7?usp=drive_link', 'Estudiar y formarnos que podemos presentar - Rechazada, no nos presentamos más porque nunca la dan', (select id from public.financiador where lower(btrim(nombre)) = lower('CES · Cuerpo Europeo de Solidaridad')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('CES24','') and nombre = 'Cuerpo Europ. Solid. 2024 R1' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('CES · Cuerpo Europeo de Solidaridad')) and convocatoria is not distinct from 'Cuerpo Europeo de la Solidaridad - Ronda 2 - 2023' and fecha_convocatoria is not distinct from '2024-02-20'::date);
-- fila 67
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto Onda', 'Entidades Juveniles', 2024, 'rechazada', 'Onda', 8000.0, null, null, '2024-03-01', null, '2024-08-01', null, null, false, false, 'BASES ESPECÍFICAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES A ASOCIACIONES Y ENTIDADES DE ONDA, SIN ÁNIMO DE LUCRO PARA LA REALIZACIÓN DE PROGRAMAS DE OCIO Y TIEMPO LIBRE DIRIGIDAS A LA POBLACIÓN JUVENIL DE ONDA (PRESUPUESTO 2023).', null, 'Rechazada porque no teníamos 2 años de antiguedad, se da solo a una entidad. Nos deberian tocar 8000 € en 2025.', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto Onda')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%onda%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto Onda','') and nombre = 'Entidades Juveniles' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'Onda' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto Onda')) and convocatoria is not distinct from 'BASES ESPECÍFICAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES A ASOCIACIONES Y ENTIDADES DE ONDA, SIN ÁNIMO DE LUCRO PARA LA REALIZACIÓN DE PROGRAMAS DE OCIO Y TIEMPO LIBRE DIRIGIDAS A LA POBLACIÓN JUVENIL DE ONDA (PRESUPUESTO 2023).' and fecha_convocatoria is not distinct from '2024-03-01'::date);
-- fila 68
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS AV', 'Llamada a Proyectos: Taller AV', 2024, 'cobrada', 'Castellón', 1625.0, 1625.0, null, '2024-03-15', null, null, null, null, false, false, 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Octubre 2023', null, 'Presentamos taller tecnica audiovisual para octubre', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS AV','') and nombre = 'Llamada a Proyectos: Taller AV' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Octubre 2023' and fecha_convocatoria is not distinct from '2024-03-15'::date);
-- fila 69
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA ESAL', 'Educacion Intercultural y valores', 2024, 'renuncia', 'AJ', 6200.0, null, null, '2024-06-27', null, null, null, '2024-11-30', false, false, 'Subvenciones destinadas a acciones y programas educativos innovadores que promuevan la educación intercultural y en valores desarrollados por entidades privadas sin ánimo de lucro en el territorio valenciano en el curso escolar 2022-2023 [RESOLUCIÓN de 3 de abril de 2023]', 'https://drive.google.com/drive/folders/1DQx7G4uOl-9PXcLk4U2qnPQ7pigEDLf3?usp=drive_link', 'Curso 2023-2024, aprovechar para presentar septiembre, octubre, noviembre, diciembre de 2023 - Llegamos tarde y no nos presentamos por error
Concesión en el Excel: 2024-05-15 (es anterior a la convocatoria: probablemente copiada de otro año, revísala)', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Educación')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA ESAL','') and nombre = 'Educacion Intercultural y valores' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Educación')) and convocatoria is not distinct from 'Subvenciones destinadas a acciones y programas educativos innovadores que promuevan la educación intercultural y en valores desarrollados por entidades privadas sin ánimo de lucro en el territorio valenciano en el curso escolar 2022-2023 [RESOLUCIÓN de 3 de abril de 2023]' and fecha_convocatoria is not distinct from '2024-06-27'::date);
-- fila 70
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS Cul', 'Cultura', 2024, 'renuncia', 'Castellón', 3900.0, null, null, '2024-05-01', null, '2024-10-01', '2025-02-01', null, false, false, 'BASES REGULADORAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES, POR PARTE DEL AYUNTAMIENTO DE CASTELLÓ DE LA PLANA, DESTINADAS A LA FINANCIACIÓN DE PROYECTOS DE DESARROLLO Y FOMENTO DE LA CULTURA QUE REALICEN LAS ASOCIACIONES CULTURALES DURANTE EL PERÍODO COMPRENDIDO ENTRE EL 1 DE ENERO Y EL 31 DE DICIEMBRE DE 2023', 'https://drive.google.com/drive/folders/1EiOGRvMf5HOKib8EWnUfVfdP42Dx33HO?usp=drive_link', 'Valorar nuevo musical Mª Rosa Molas, los gastos deben ejecutarse en 2024 - No nos presentamos, valoramos 2025, 2026', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS Cul','') and nombre = 'Cultura' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'BASES REGULADORAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES, POR PARTE DEL AYUNTAMIENTO DE CASTELLÓ DE LA PLANA, DESTINADAS A LA FINANCIACIÓN DE PROYECTOS DE DESARROLLO Y FOMENTO DE LA CULTURA QUE REALICEN LAS ASOCIACIONES CULTURALES DURANTE EL PERÍODO COMPRENDIDO ENTRE EL 1 DE ENERO Y EL 31 DE DICIEMBRE DE 2023' and fecha_convocatoria is not distinct from '2024-05-01'::date);
-- fila 71
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'IVAJ', 'Entidades Juveniles', 2024, 'rechazada', 'AJ', 30000.0, null, null, '2024-06-17', null, '2024-08-01', null, null, false, false, 'Asociaciones IVAJ', null, 'Estudiar. Contratación técnico + Curso MAT + Actividades grandes a cofinanciar. Rechazada porque no llegamos a los 10 ayuntamientos necesarios. Casi garantizada 2025.', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IVAJ')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('IVAJ','') and nombre = 'Entidades Juveniles' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IVAJ')) and convocatoria is not distinct from 'Asociaciones IVAJ' and fecha_convocatoria is not distinct from '2024-06-17'::date);
-- fila 72
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'DIP CS', 'Entidades Juveniles CS', 2024, 'cobrada', 'Castellón', 5000.0, 1880.0, null, '2024-04-29', null, '2024-11-01', '2024-12-29', null, true, true, 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023', 'https://drive.google.com/drive/folders/1QXXs6qGaIuK4QsbaSPOETMYEPT7VYJB6?usp=drive_link', 'Campamento Castellón - Solo presentar 5.000 €
Sobre el importe: revisar!!!', (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('DIP CS','') and nombre = 'Entidades Juveniles CS' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')) and convocatoria is not distinct from 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023' and fecha_convocatoria is not distinct from '2024-04-29'::date);
-- fila 73
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'DIP VIL', 'Entidades Juveniles VILA', 2024, 'cobrada', 'Vila-real', 5000.0, 1880.0, null, '2024-04-29', null, '2024-11-01', '2024-12-29', null, true, true, 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023', 'https://drive.google.com/drive/folders/1QXXs6qGaIuK4QsbaSPOETMYEPT7VYJB6?usp=drive_link', 'Campamento Vila-real- Solo presentar 5.000 €', (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%vila%real%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('DIP VIL','') and nombre = 'Entidades Juveniles VILA' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'Vila-real' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')) and convocatoria is not distinct from 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023' and fecha_convocatoria is not distinct from '2024-04-29'::date);
-- fila 74
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS', 'Entidades Juveniles', 2024, 'cobrada', 'Castellón', 6000.0, 6481.54, null, '2024-09-01', null, '2024-12-01', '2025-08-15', null, true, true, 'Concessió de Subvencions a Entitats Juvenils per a l''execució d''activitats durant el període comprés entre l''1 de Juliol de 2023 i el 30 de juny de 2024', 'https://drive.google.com/drive/u/0/folders/11TRr4SqYxZp8GrM07tkxrVPlnWFVnqwp', 'Campamento Consolación Castellón + otras 2 actividades
Sobre el importe: 2.617 - Acampada COM 3864.54 € - Campamento Pago del 50 % en primer lugar 1308.5 + 1932.27 €', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS','') and nombre = 'Entidades Juveniles' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Concessió de Subvencions a Entitats Juvenils per a l''execució d''activitats durant el període comprés entre l''1 de Juliol de 2023 i el 30 de juny de 2024' and fecha_convocatoria is not distinct from '2024-09-01'::date);
-- fila 76
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'KIT ECE', 'Kit Digital AJ / ECE', 2024, 'renuncia', 'ECE', 3000.0, null, null, null, null, null, null, null, false, false, null, null, 'Valorar volver a presentarnos como ECE', (select id from public.financiador where lower(btrim(nombre)) = lower('Red.es')), null, '[{"nombre": "Red.es", "url": "http://red.es/"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('KIT ECE','') and nombre = 'Kit Digital AJ / ECE' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'ECE' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Red.es')) and convocatoria is not distinct from null and fecha_convocatoria is not distinct from null::date);
-- fila 78
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA VAL', 'Fomento Valencià', 2024, 'renuncia', 'AJ', 3000.0, null, null, '2024-01-01', null, null, null, null, false, false, null, 'https://ceice.gva.es/es/web/dgplgm/associacions', null, (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Educación')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA VAL','') and nombre = 'Fomento Valencià' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Educación')) and convocatoria is not distinct from null and fecha_convocatoria is not distinct from '2024-01-01'::date);
-- fila 79
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA ODS', 'ODS', 2024, 'renuncia', 'AJ', null, null, null, '2024-06-01', null, null, null, null, false, false, null, 'https://inclusio.gva.es/va/web/cooperacion/seguimiento-de-las-convocatorias', 'Parece que ya no está saliendo
Importe: Hasta 20k', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA ODS','') and nombre = 'ODS' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión')) and convocatoria is not distinct from null and fecha_convocatoria is not distinct from '2024-06-01'::date);
-- fila 80
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA IRPF', 'Entidades Juveniles / Voluntariado', 2024, 'renuncia', 'AJ', null, null, null, '2024-06-01', null, '2024-12-01', null, null, false, false, null, 'https://inclusio.gva.es/va/web/cooperacion/seguimiento-de-las-convocatorias', 'En principio no podemos presentarnos por 2 años de antiguedad
Importe: Hasta 30k', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IRPF')), null, '[]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA IRPF','') and nombre = 'Entidades Juveniles / Voluntariado' and ejercicio is not distinct from 2024::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA IRPF')) and convocatoria is not distinct from null and fecha_convocatoria is not distinct from '2024-06-01'::date);
-- fila 84
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'KIT ECE', 'Kit Digital', 2023, 'cobrada', 'ECE', 2000.0, 2000.0, null, '2023-09-02', null, '2023-12-22', '2024-06-22', null, false, false, null, 'https://drive.google.com/drive/folders/1KmorbFwQ9rhH01geoU6LdIa1fO5_e4Ig?usp=drive_link', 'Solo se presenta una única vez - Valorar volver a presentarnos como MCM España (Asoc. Religiosa)
2ª justificación: +3 meses desde firma
Justificación: Antes del 22 de junio debe estar decidido quién se va a encargar y tener la tarea encargada
Qué se presenta: Renovación webs del MCM movimientoconsolacion.es movimientoconsolacion.com aj.movimientoconsolacion.es (nueva)', (select id from public.financiador where lower(btrim(nombre)) = lower('Red.es')), null, '[{"nombre": "Red.es", "url": "http://red.es/"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('KIT ECE','') and nombre = 'Kit Digital' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'ECE' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Red.es')) and convocatoria is not distinct from null and fecha_convocatoria is not distinct from '2023-09-02'::date);
-- fila 85
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA VOL', 'Fom. Voluntariado', 2023, 'cobrada', 'AJ', 11400.0, 11400.0, null, '2022-12-29', null, '2023-07-13', '2023-09-11', '2023-10-31', true, true, 'Convocatoria de subvenciones para el ejercicio 2023 a entidades privadas sin ánimo de lucro para la financiación de proyectos de proyectos y actividades de promoción y fomento del voluntariado en la Comunitat Valenciana', 'https://drive.google.com/drive/folders/17_I5in9UkNM_t8i37U0HOQhH6ExiXtgS?usp=drive_link', 'Ampliar a 15.000 € - Incluir hasta 7.000 € de sueldo técnico. Funciona correctamente y sin sorpresas.
2ª justificación: Memoria técnica: 19 enero 2024
Qué se presenta: Gastos generales del año, actividades vinculadas con la formación de monitores, convivencias de monitores, merchandasing, material general de los proyectos... No aceptan material inventariable, pero sí material de oficina y actividades.', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión')), null, '[{"nombre": "Readme - Subvención GVA Voluntariado 2023", "url": "https://docs.google.com/document/d/1JKGZsWRZART9o-fJWB0woqLm6G7XLxlqzhbbFhBGv6w/edit"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA VOL','') and nombre = 'Fom. Voluntariado' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Inclusión')) and convocatoria is not distinct from 'Convocatoria de subvenciones para el ejercicio 2023 a entidades privadas sin ánimo de lucro para la financiación de proyectos de proyectos y actividades de promoción y fomento del voluntariado en la Comunitat Valenciana' and fecha_convocatoria is not distinct from '2022-12-29'::date);
-- fila 86
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'GVA ESAL', 'Educacion Intercultural y valores', 2023, 'cobrada', 'AJ', 6200.0, 3630.0, null, '2023-04-03', null, '2023-05-25', null, '2023-11-30', true, false, 'Subvenciones destinadas a acciones y programas educativos innovadores que promuevan la educación intercultural y en valores desarrollados por entidades privadas sin ánimo de lucro en el territorio valenciano en el curso escolar 2022-2023 [RESOLUCIÓN de 3 de abril de 2023]', 'https://drive.google.com/drive/folders/1DQx7G4uOl-9PXcLk4U2qnPQ7pigEDLf3?usp=drive_link', 'Desde sept-22 a ago-23, es la única que va por curso académico. Sirve para cubrir el final de año que no has podido presentar en las demás (sept-dic)
Qué se presenta: Castellón: Impresiones, bus convivencia, bus intermedio acampada Onda: Autobús e impresiones campamento. Samuel: Camisetas', (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Educación')), null, '[{"nombre": "Readme - Subvención Programas Educativos 2023", "url": "https://docs.google.com/document/d/1ZgS9bM8M6qpjJt3Gn2YRkXcBUEa8LEsHPEAWGaKIik8/edit?usp=drive_link"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('GVA ESAL','') and nombre = 'Educacion Intercultural y valores' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'AJ' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('GVA Educación')) and convocatoria is not distinct from 'Subvenciones destinadas a acciones y programas educativos innovadores que promuevan la educación intercultural y en valores desarrollados por entidades privadas sin ánimo de lucro en el territorio valenciano en el curso escolar 2022-2023 [RESOLUCIÓN de 3 de abril de 2023]' and fecha_convocatoria is not distinct from '2023-04-03'::date);
-- fila 87
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'DIP CS', 'Entidades Juveniles CS', 2023, 'cobrada', 'Castellón', 37880.0, 2990.97, null, '2023-07-03', null, '2023-11-06', '2023-12-29', null, true, true, 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023', 'https://drive.google.com/drive/folders/1QXXs6qGaIuK4QsbaSPOETMYEPT7VYJB6?usp=drive_link', 'Hay que justificar lo que solicitas (37k€) por lo que es mejor pedir solo 5k€ - Nos cuelan < 12 años, pero no será así en el futuro. Presentar solo +12 años. Presentar solo la factura del alojamiento, separada por edad
Qué se presenta: Campamento Consolación Castellón - 3000 € Alojamiento y otros gastos NO era necesario otros gastos', (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[{"nombre": "Readme - Subvención Dipu CS 2023", "url": "https://docs.google.com/document/d/1MlD_WeIFMV4nFHQ5TrhOcPk_BSFsQNUm92lYGjOqNYo/edit?usp=drive_link"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('DIP CS','') and nombre = 'Entidades Juveniles CS' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')) and convocatoria is not distinct from 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023' and fecha_convocatoria is not distinct from '2023-07-03'::date);
-- fila 88
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'DIP VIL', 'Entidades Juveniles VILA', 2023, 'cobrada', 'Vila-real', 30098.0, 3000.0, null, '2023-07-03', null, '2023-11-06', '2023-12-29', null, true, true, 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023', 'https://drive.google.com/drive/folders/1QXXs6qGaIuK4QsbaSPOETMYEPT7VYJB6?usp=drive_link', 'Hay que justificar lo que solicitas (37k€) por lo que es mejor pedir solo 5k€ - Nos cuelan < 12 años, pero no será así en el futuro. Presentar solo +12 años. Presentar solo la factura del alojamiento, separada por edad
Qué se presenta: Campamento Consolación Vila-real - 3000 € Solo la factura de alojamiento (30k€)', (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%vila%real%'), '[{"nombre": "Readme - Subvención Dipu CS 2023", "url": "https://docs.google.com/document/d/1MlD_WeIFMV4nFHQ5TrhOcPk_BSFsQNUm92lYGjOqNYo/edit?usp=drive_link"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('DIP VIL','') and nombre = 'Entidades Juveniles VILA' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'Vila-real' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Diputación CS')) and convocatoria is not distinct from 'CONCRECIÓ DE LES BASES PER LES QUALS ES REGEIX LA CONCESSIÓ DE SUBVENCIONS A ASSOCIACIONS JUVENILS DE LA PROVÍNCIA DE CASTELLÓ PER A PROGRAMES DE JOVENTUT. EXERCICI 2023' and fecha_convocatoria is not distinct from '2023-07-03'::date);
-- fila 89
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'CES23', 'Cuerpo Europ. Solid. 2023 R2', 2023, 'rechazada', 'Castellón', 8130.0, null, null, '2023-10-04', null, '2023-12-22', null, null, false, false, 'Cuerpo Europeo de la Solidaridad - Ronda 2 - 2023', 'https://drive.google.com/drive/folders/1YoVRByPp_iI7WitGMcjqVoo3wU3vkMN7?usp=drive_link', 'Rechazada porque no somos suficientemente claros. Necesario darle una vuelta y formarse para acceder a esta financiación. Próximo
Qué se presenta: Grupo informal de jóvenes vinculado a la asociación. Los gastos no se justifican directamente', (select id from public.financiador where lower(btrim(nombre)) = lower('CES · Cuerpo Europeo de Solidaridad')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[{"nombre": "AJMCM · CES 2024 · Textos para el Proyecto", "url": "https://docs.google.com/document/d/1UnYlDNZovoNbdGDGMOw-ugSw6QuZ9MKulWWSJZUd6Uk/edit?usp=drive_link"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('CES23','') and nombre = 'Cuerpo Europ. Solid. 2023 R2' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('CES · Cuerpo Europeo de Solidaridad')) and convocatoria is not distinct from 'Cuerpo Europeo de la Solidaridad - Ronda 2 - 2023' and fecha_convocatoria is not distinct from '2023-10-04'::date);
-- fila 90
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS Cul', 'Cultura', 2023, 'cobrada', 'Castellón', 3900.0, 1715.69, null, '2023-05-02', null, '2023-09-29', '2024-02-29', null, true, false, 'BASES REGULADORAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES, POR PARTE DEL AYUNTAMIENTO DE CASTELLÓ DE LA PLANA, DESTINADAS A LA FINANCIACIÓN DE PROYECTOS DE DESARROLLO Y FOMENTO DE LA CULTURA QUE REALICEN LAS ASOCIACIONES CULTURALES DURANTE EL PERÍODO COMPRENDIDO ENTRE EL 1 DE ENERO Y EL 31 DE DICIEMBRE DE 2023', 'https://drive.google.com/drive/folders/1EiOGRvMf5HOKib8EWnUfVfdP42Dx33HO?usp=drive_link', 'Se puede pedir anualmente, pero hay que tener proyectos culturales en la Ciudad de Castellón
Qué se presenta: Musical La Fuerza de un Sueño Gastos efectuados durante el musical que quedarán como remanente para Pastoral Juvenil + Colegio de Castellón (renovación material audiovisual)', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[{"nombre": "2023 - CS Ayto - Cultura - Musical MTGJ", "url": "https://drive.google.com/drive/u/0/folders/1EiOGRvMf5HOKib8EWnUfVfdP42Dx33HO"}, {"nombre": "Proyecto Cultural - Musical La Fuerza de un Sueño", "url": "https://docs.google.com/document/d/1bLG0C2NByLtMeueyNO4NJD5MFSZ0xMQi-GfMjvRo1sc/edit"}, {"nombre": "Presupuesto Subvención MTGJ", "url": "https://docs.google.com/spreadsheets/d/1Bz8ME9ea2Milm4LcWHGUYwapUzNKflt5B0CFDHh9iRY/edit"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS Cul','') and nombre = 'Cultura' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'BASES REGULADORAS DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES, POR PARTE DEL AYUNTAMIENTO DE CASTELLÓ DE LA PLANA, DESTINADAS A LA FINANCIACIÓN DE PROYECTOS DE DESARROLLO Y FOMENTO DE LA CULTURA QUE REALICEN LAS ASOCIACIONES CULTURALES DURANTE EL PERÍODO COMPRENDIDO ENTRE EL 1 DE ENERO Y EL 31 DE DICIEMBRE DE 2023' and fecha_convocatoria is not distinct from '2023-05-02'::date);
-- fila 91
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS', 'Entidades Juveniles', 2023, 'cobrada', 'Castellón', 5250.0, 2517.0, null, '2023-09-15', null, '2023-12-19', '2024-08-15', null, true, true, 'Concessió de Subvencions a Entitats Juvenils per a l''execució d''activitats durant el període comprés entre l''1 de Juliol de 2023 i el 30 de juny de 2024', 'https://drive.google.com/drive/u/0/folders/11TRr4SqYxZp8GrM07tkxrVPlnWFVnqwp', 'Se presentan dos actividades, presentables hasta 3. Proyecto con máxima puntuación de los presentados.
Qué se presenta: Campamento Consolación Castellón - 4000 € Acampada Inicio Curso COM - 1250 € Se concede menos', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[{"nombre": "Readme - Subvención Ayuntamiento 2023", "url": "https://docs.google.com/document/d/1kUhiVvuSANidVl6j6rb5bWseIfvChXzSv6lrRAysD-I/edit"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS','') and nombre = 'Entidades Juveniles' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Concessió de Subvencions a Entitats Juvenils per a l''execució d''activitats durant el període comprés entre l''1 de Juliol de 2023 i el 30 de juny de 2024' and fecha_convocatoria is not distinct from '2023-09-15'::date);
-- fila 92
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS Lan', 'Llamada a Proyectos: Lan Party 24', 2023, 'cobrada', 'Castellón', 2875.0, 2875.0, null, '2023-10-15', null, null, null, null, true, true, 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Abril 2024', 'https://drive.google.com/drive/folders/1lF2Vdjf56NMbt60ajy6OExsfxfdVLfpB?usp=drive_link', 'Se trata de un contrato no de una subvención, por lo que no se justifican los gastos, solo se entrega documentación. Se cobra 2024
2ª justificación: Pagada junio 24
Qué se presenta: Gastos vinculados a la "actividad extraordinaria de ocio educativo" Lan Party MCM 2024', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[{"nombre": "Llamada Proyecto Lan Party 2024 - Presentado Oct 2023", "url": "https://docs.google.com/document/d/1De1eFY3UMFE9y8HvmB9I8UCW01Pyf_t4ySxzYV4JYEM/edit?usp=drive_link"}, {"nombre": "Presupuesto Lan Party 2024", "url": "https://docs.google.com/spreadsheets/d/1_JAN_qeLk533wPy_481NxUNStLgfjQa3KWR0xq1nahM/edit?usp=drive_link"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS Lan','') and nombre = 'Llamada a Proyectos: Lan Party 24' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Abril 2024' and fecha_convocatoria is not distinct from '2023-10-15'::date);
-- fila 93
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS AV', 'Llamada a Proyectos: Taller AV', 2023, 'cobrada', 'Castellón', 960.0, 960.0, null, '2022-10-31', null, '2022-12-19', '2023-02-27', null, true, true, 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Febrero 2023', 'https://drive.google.com/drive/folders/1eE1lJdBoU3hrmLO_plN6o0F2L52e72-B?usp=drive_link', 'Se trata de un contrato no de una subvención, por lo que no se justifican los gastos, solo se entrega documentación
Qué se presenta: No se justifican los gastos, el total es beneficio para la hucha "MCM Castellón" dentro de la cuenta bancaria de la Asociación Juvenil', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[{"nombre": "Proyecto Taller Técnica AV - Febrero 2023 - Presentado Octubre 2022", "url": "https://docs.google.com/document/d/1xBminAz4kH6rRnlG7tdxdoe8HFYeojTDTQKUzER3Lfo/edit?usp=drive_link"}, {"nombre": "Presupuesto Taller 2022", "url": "https://docs.google.com/spreadsheets/d/1C7T33HhFCnJ_DebQRf0lh_ffUtKEEO8baJNOyIt64wo/edit?usp=drive_link"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS AV','') and nombre = 'Llamada a Proyectos: Taller AV' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Febrero 2023' and fecha_convocatoria is not distinct from '2022-10-31'::date);
-- fila 94
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS AV', 'Llamada a Proyectos: Taller AV', 2023, 'rechazada', 'Castellón', 1625.0, null, null, '2023-03-15', null, null, null, null, false, false, 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Octubre 2023', 'https://drive.google.com/drive/u/0/folders/11o-6-KpBj_hZXv7tjm9ff2EA96-zmqJP', 'Rechazada porque no tuvimos en cuenta que los talleres tienen duración máxima 2h', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[{"nombre": "Proyecto Taller Técnica AV - Octubre 2023 - Presentado Marzo 2023", "url": "https://docs.google.com/document/d/1HSIGZPrfYJb1veiIzNhhMw4UGA8UxBk5nmVkLRBdlCA/edit"}, {"nombre": "Presupuesto Taller 2023", "url": "https://docs.google.com/spreadsheets/d/1s7tps_rPvMzqvd6X0BzukXK6OylhJmJcmU_7-TMEPSA/edit"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS AV','') and nombre = 'Llamada a Proyectos: Taller AV' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut” - Octubre 2023' and fecha_convocatoria is not distinct from '2023-03-15'::date);
-- fila 95
insert into public.subvencion (codigo, nombre, ejercicio, estado, solicitante, importe_solicitado, importe_concedido, importe_cobrado, fecha_convocatoria, fecha_limite_solicitud, fecha_concesion, fecha_justificacion_1, fecha_justificacion_2, justificacion_completa, recurrente, convocatoria, url_carpeta, notas, financiador_id, delegacion_id, enlaces)
select 'Ayto CS AV', 'Llamada a Proyectos: Taller AV', 2023, 'rechazada', 'Castellón', 1300.0, null, null, '2023-10-15', null, null, null, null, false, false, 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut”', 'https://drive.google.com/drive/u/0/folders/11o-6-KpBj_hZXv7tjm9ff2EA96-zmqJP', 'Rechazada porque nos aceptan la Lan Party y sino sería abusar. Plantear presentarla a la siguiente. Previsto cobrar formadores
Qué se presenta: No se justifican los gastos, el total es beneficio para la hucha "MCM Castellón" dentro de la cuenta bancaria de la Asociación Juvenil', (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')), (select case when count(*) = 1 then (array_agg(id))[1] end from public.delegacion where lower(nombre) like '%castell%'), '[{"nombre": "Proyecto Taller Técnica AV - Febrero 2024 - Presentado Octubre 2023", "url": "https://docs.google.com/document/d/1SAIgzzZ2O-4HvdfQ6qeM_O5R5L3tEmDFJ30xph4gPd0/edit"}, {"nombre": "Presupuesto Taller 2024 · Presentado oct 2023", "url": "https://docs.google.com/spreadsheets/d/1Gjt90XO26T0udPlvmlHyErQxbKfENgYtby4VY6tjDPo/edit"}]'::jsonb
where not exists (select 1 from public.subvencion where coalesce(codigo,'') = coalesce('Ayto CS AV','') and nombre = 'Llamada a Proyectos: Taller AV' and ejercicio is not distinct from 2023::int and solicitante is not distinct from 'Castellón' and financiador_id is not distinct from (select id from public.financiador where lower(btrim(nombre)) = lower('Ayto CS')) and convocatoria is not distinct from 'Bases “Crida a projectes d’Activitats d’Oci Educatiu de la Regidoria de Joventut”' and fecha_convocatoria is not distinct from '2023-10-15'::date);

commit;
